import { boolean, index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

/**
 * Repo registry — the first-class repository entity for multi-repo work.
 *
 * See `.octipus/multi-repo-design.md`. Octipus is otherwise architected
 * around a single working root per session (`SessionContext.projectPath`).
 * In a suite of interconnected products + libraries, agents need a *map of
 * the suite*: which repos exist, what each is for, and how they depend on
 * each other — built once and navigated by, not rediscovered per session.
 *
 * A row is one repository on disk (a directory with a project marker —
 * `.git`, `package.json`, `Cargo.toml`, …). The scanner
 * (`src/core/repos/scanner.ts`) detects markers, languages, manifests, the
 * git remote, and a compact structural digest, then upserts here. Dependency
 * edges between repos are derived by matching each repo's manifest
 * dependencies against the `packageName` of other registry rows — so the
 * graph lives in plain code over these rows, no second table.
 */

/** A single manifest-declared dependency. */
export interface RepoDependency {
  /** Declared package name, e.g. "@acme/core" or "github.com/acme/lib". */
  name: string;
  /** Version constraint as written in the manifest (e.g. "^2.1.0"). */
  version: string;
  /** Which manifest it came from: "package.json" | "Cargo.toml" | "go.mod" | "pyproject.toml". */
  manifest: string;
}

/** Coarse classification used for routing and display. */
export type RepoKind = 'product' | 'library' | 'app' | 'infra' | 'unknown';

export const workspaceRepos = pgTable('workspace_repos', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  /** Optional workspace scope. NULL = user-level. Mirrors the rest of the schema. */
  workspaceId: uuid('workspace_id'),
  /** Display name — the directory name unless overridden. */
  name: text('name').notNull(),
  /** Absolute path to the repository root on disk. Unique per owner. */
  rootPath: text('root_path').notNull(),
  /** Git remote URL, when the repo has one. */
  remoteUrl: text('remote_url'),
  /** Default branch (e.g. "main"), when detectable. */
  defaultBranch: text('default_branch'),
  /** product | library | app | infra | unknown. Plain text so new kinds need no migration. */
  kind: text('kind').notNull().default('unknown'),
  /** Detected languages, e.g. ["typescript", "rust"]. */
  languages: text('languages').array().notNull().default([]),
  /**
   * Canonical package name this repo publishes (from its own manifest), used
   * to match other repos' dependencies back to this row when building the
   * dependency graph. NULL when the repo declares no package name.
   */
  packageName: text('package_name'),
  /** Manifest-declared dependencies — the raw edges out of this repo. */
  dependencies: jsonb('dependencies').$type<RepoDependency[]>().notNull().default([]),
  /**
   * Compact structural digest (top-level dirs, entry points, commands) — the
   * cheap "mental model" injected when an agent enters the repo, instead of
   * re-reading the tree. Generated by the scanner; NULL until first scan.
   */
  repoMap: text('repo_map'),
  /** Whether the repo carries a curated AGENTS.md at its root. */
  hasAgentsMd: boolean('has_agents_md').notNull().default(false),
  /** Last time the scanner refreshed this row. NULL = registered but never scanned. */
  lastScannedAt: timestamp('last_scanned_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  // A repo path is unique per owner — re-scanning upserts rather than duplicates.
  pathUserIdx: uniqueIndex('workspace_repos_user_path_uidx').on(table.userId, table.rootPath),
  userIdx: index('workspace_repos_user_idx').on(table.userId),
  packageNameIdx: index('workspace_repos_package_name_idx').on(table.packageName),
}));

export type WorkspaceRepo = typeof workspaceRepos.$inferSelect;
export type NewWorkspaceRepo = typeof workspaceRepos.$inferInsert;
