#!/usr/bin/env bun
/**
 * Minimal setup wizard — generates bootstrap .env file.
 * All other configuration (LLM, channels, workspace, etc.) is done
 * via the web UI at /setup after first boot.
 */

import { createInterface } from 'readline';
import { existsSync } from 'fs';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

const prompt = (question: string): Promise<string> => {
  return new Promise((resolve) => {
    rl.question(question, resolve);
  });
};

const confirm = async (question: string, defaultYes = true): Promise<boolean> => {
  const suffix = defaultYes ? '[Y/n]' : '[y/N]';
  const answer = await prompt(`${question} ${suffix}: `);
  if (!answer.trim()) return defaultYes;
  return answer.toLowerCase().startsWith('y');
};

function generateSecureKey(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Buffer.from(bytes).toString('base64');
}

async function main(): Promise<void> {
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║     █████╗ ███████╗███████╗██╗███████╗████████╗          ║
║    ██╔══██╗██╔════╝██╔════╝██║██╔════╝╚══██╔══╝          ║
║    ███████║███████╗███████╗██║███████╗   ██║             ║
║    ██╔══██║╚════██║╚════██║██║╚════██║   ██║             ║
║    ██║  ██║███████║███████║██║███████║   ██║             ║
║    ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚══════╝   ╚═╝             ║
║                                                           ║
║              Bootstrap Setup                              ║
╚═══════════════════════════════════════════════════════════╝
`);

  // Check if .env already exists
  if (existsSync('.env')) {
    const overwrite = await confirm('.env already exists. Overwrite?', false);
    if (!overwrite) {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('This wizard creates a minimal .env with database and security settings.');
  console.log('All other configuration is done via the web UI after first boot.\n');

  // ─── Database ───
  console.log('── Database ──');
  const dbHost = (await prompt('PostgreSQL host [localhost]: ')).trim() || 'localhost';
  const dbPort = (await prompt('PostgreSQL port [5432]: ')).trim() || '5432';
  const dbName = (await prompt('Database name [assistant]: ')).trim() || 'assistant';
  const dbUser = (await prompt('Database user [assistant]: ')).trim() || 'assistant';
  const dbPassword = await prompt('Database password: ');
  const databaseUrl = `postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}`;

  // ─── Redis ───
  console.log('\n── Redis ──');
  const redisHost = (await prompt('Redis host [localhost]: ')).trim() || 'localhost';
  const redisPort = (await prompt('Redis port [6379]: ')).trim() || '6379';
  const redisPassword = await prompt('Redis password (leave empty if none): ');
  const redisUrl = redisPassword
    ? `redis://:${redisPassword}@${redisHost}:${redisPort}`
    : `redis://${redisHost}:${redisPort}`;

  // ─── API ───
  console.log('\n── API Server ──');
  const port = (await prompt('API port [3005]: ')).trim() || '3005';
  const host = (await prompt('API host [0.0.0.0]: ')).trim() || '0.0.0.0';

  // ─── Security keys (auto-generated) ───
  console.log('\n── Security ──');
  const masterKey = generateSecureKey();
  const jwtSecret = generateSecureKey();
  const sessionSecret = generateSecureKey();
  console.log('Security keys auto-generated (32 bytes each).');

  // ─── Write .env ───
  const envContent = `# Bootstrap Configuration (generated by setup wizard)
# ${new Date().toISOString()}
#
# All other settings (LLM, channels, workspace, etc.) are configured
# via the web UI at http://localhost:${port}/setup

# Database
DATABASE_URL=${databaseUrl}
REDIS_URL=${redisUrl}

# Security (auto-generated, do not share)
MASTER_KEY=${masterKey}
JWT_SECRET=${jwtSecret}
SESSION_SECRET=${sessionSecret}

# API Server
PORT=${port}
HOST=${host}
`;

  await Bun.write('.env', envContent);
  console.log('\n✅ Bootstrap .env created');

  // ─── Summary ───
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║                    SETUP COMPLETE                         ║
╚═══════════════════════════════════════════════════════════╝

Next steps:
  1. Start the server:  bun run dev
  2. Open the setup wizard:  http://localhost:${port}/setup
  3. Create your admin account and configure LLM, channels, etc.

The web setup wizard will guide you through the remaining configuration.
`);

  rl.close();
}

main().catch((error) => {
  console.error('Setup failed:', error);
  rl.close();
  process.exit(1);
});
