import { resolve } from 'path';
import { getConfig } from '@/config';
import { coreLogger } from '@/utils/logger';
import type { AgentContext } from '@/core/types';

/**
 * Auto-update .assistant/project-summary.md after pipeline/agent completion.
 * Appends a timestamped entry with the pipeline results.
 * Creates the file if it doesn't exist.
 */
export async function autoUpdateProjectSummary(
  context: AgentContext,
  title: string,
  output: string,
): Promise<void> {
  try {
    // Gate: only dev sessions get project-summary auto-writes.
    // Non-dev sessions rely on RAG/knowledge base for cross-session recall.
    const session = await (await import('@/db/repositories/session-repository')).sessionRepository.findById(context.sessionId);
    const sessionCtx = session?.context as { devMode?: boolean; projectPath?: string } | undefined;

    if (!sessionCtx?.devMode || !sessionCtx?.projectPath) {
      return;
    }

    const projectRoot = sessionCtx.projectPath;

    // Guard: never write project summaries inside session folders
    const resolvedRoot = resolve(projectRoot);
    const sessionsDir = resolve(getConfig().workspace?.rootPath || '.', 'sessions');
    if (resolvedRoot.startsWith(sessionsDir)) {
      coreLogger.warn({ projectRoot, sessionsDir }, 'Skipping project summary — resolved path is inside sessions directory');
      return;
    }

    const summaryDir = resolve(projectRoot, '.assistant');
    const summaryPath = resolve(summaryDir, 'project-summary.md');
    const { mkdirSync, existsSync, readFileSync, writeFileSync } = await import('fs');

    // Ensure .assistant/ directory exists — this is the most common failure point
    try {
      mkdirSync(summaryDir, { recursive: true });
    } catch (dirErr) {
      coreLogger.error({ err: dirErr, summaryDir }, 'Failed to create .assistant/ directory for project summary');
      return;
    }

    // Read existing summary
    let existing = '';
    if (existsSync(summaryPath)) {
      existing = readFileSync(summaryPath, 'utf-8');
    }

    // Create a concise summary entry from the output
    const timestamp = new Date().toISOString().split('T')[0];
    const truncatedOutput = output.length > 2000
      ? output.slice(0, 2000) + '\n\n[... truncated]'
      : output;

    const entry = `\n\n## ${title} (${timestamp})\n\n${truncatedOutput}\n`;

    // Append to existing summary (or create new)
    if (existing) {
      writeFileSync(summaryPath, existing + entry, 'utf-8');
    } else {
      const header = `# Project Summary\n\nAuto-generated by the assistant after pipeline/agent runs.\n`;
      writeFileSync(summaryPath, header + entry, 'utf-8');
    }

    coreLogger.info({ projectRoot, title }, 'Project summary updated');
  } catch (err) {
    coreLogger.error({ err, sessionId: context.sessionId, role: context.role, title }, 'Failed to auto-update project summary');
  }
}
