import { resolve } from 'path';
import { getConfig } from '@/config';
import { coreLogger } from '@/utils/logger';
import type { AgentContext } from '@/core/types';

/**
 * Auto-update .assistant/project-summary.md after pipeline/agent completion.
 * Appends a timestamped entry with the pipeline results.
 * Creates the file if it doesn't exist.
 */
export async function autoUpdateProjectSummary(
  context: AgentContext,
  title: string,
  output: string,
): Promise<void> {
  try {
    // Determine project root — dev mode uses projectPath, otherwise workspace root
    const session = await (await import('@/db/repositories/session-repository')).sessionRepository.findById(context.sessionId);
    const sessionCtx = session?.context as { devMode?: boolean; projectPath?: string } | undefined;

    let projectRoot: string;
    if (sessionCtx?.devMode && sessionCtx?.projectPath) {
      projectRoot = sessionCtx.projectPath;
    } else {
      projectRoot = resolve(getConfig().workspace?.rootPath || '.');
    }

    const summaryDir = resolve(projectRoot, '.assistant');
    const summaryPath = resolve(summaryDir, 'project-summary.md');
    const { mkdirSync, existsSync, readFileSync, writeFileSync } = await import('fs');

    mkdirSync(summaryDir, { recursive: true });

    // Read existing summary
    let existing = '';
    if (existsSync(summaryPath)) {
      existing = readFileSync(summaryPath, 'utf-8');
    }

    // Create a concise summary entry from the output
    const timestamp = new Date().toISOString().split('T')[0];
    const truncatedOutput = output.length > 2000
      ? output.slice(0, 2000) + '\n\n[... truncated]'
      : output;

    const entry = `\n\n## ${title} (${timestamp})\n\n${truncatedOutput}\n`;

    // Append to existing summary (or create new)
    if (existing) {
      writeFileSync(summaryPath, existing + entry, 'utf-8');
    } else {
      const header = `# Project Summary\n\nAuto-generated by the assistant after pipeline/agent runs.\n`;
      writeFileSync(summaryPath, header + entry, 'utf-8');
    }

    coreLogger.info({ projectRoot, title }, 'Project summary updated');
  } catch (err) {
    coreLogger.warn({ err }, 'Failed to auto-update project summary');
  }
}
